### PR TITLE
[Wrong] Remove field settings form the dca.

### PR DESCRIPTION
**Pull request by baumannsven**
The field settings are defined by attribute_file.

### CODE REVIEW

**Comment by discordier** [comment]
Not really, now we have to add a requirement on `attribute_file` as otherwise the fields will not get defined at all!

**Comment by zonky2** [comment]
@discordier nu RTM ?

**Comment by zonky2** [comment]
@discordier pls check this PR again...

**Comment by zonky2** [comment]
@discordier see https://github.com/MetaModels/attribute_translatedfile/pull/14#issuecomment-336359175

**Comment by zonky2** [comment]
wie in MM-call beschlossen, soll es (möglichst) keine Abhängigkeiten zwischen den Attributen geben...

**Pull request closed without merging**
